In [4]:
import numpy as np

In [19]:
a = np.array([[6,3,6,89,32],[45,23,56,34,89]])

In [6]:
#all zoros matrix
np.zeros((4,6,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
#all ones matrix
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
# all same element
np.full((3,3),56,dtype='int16')

array([[56, 56, 56],
       [56, 56, 56],
       [56, 56, 56]], dtype=int16)

In [20]:
# full_like
np.full_like(a, 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [26]:
#random decimal matrix
np.random.rand(7,2)
np.random.rant_sample()

array([[0.38038333, 0.1484237 ],
       [0.05628026, 0.39947983],
       [0.3658421 , 0.53096308],
       [0.04968951, 0.00339617],
       [0.98950776, 0.82696379],
       [0.29821679, 0.60548285],
       [0.35911714, 0.87395693]])

In [42]:
#random integer values
np.random.randint(3,6,size=(4,3))

array([[3, 4, 4],
       [5, 5, 5],
       [5, 3, 4],
       [5, 5, 4]])

In [5]:
# identity matrix
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [19]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output [1:4,1:4] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
