In [8]:
import numpy as np

In [13]:
a = np.array([[2,3,4,5,6,7,8,9],[8,7,6,5,4,3,2,4]])
print(a)

[[2 3 4 5 6 7 8 9]
 [8 7 6 5 4 3 2 4]]


In [34]:
# Get specific element [r,c]
print(a[1, 7])

4


In [36]:
# Get specific row
a[0,:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Get specific colume
a[:,5]

array([7, 3])

In [52]:
a[0,0:9:1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a[1,5] = 89
print(a)
a[:,4]=20
print(a)

[[ 2  3  4  5 20  7  8  9]
 [ 8  7  6  5 20 89  2  4]]
[[ 2  3  4  5 20  7  8  9]
 [ 8  7  6  5 20 89  2  4]]


In [59]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [64]:
print(b[1,0,1])

6


In [72]:
b[:,1,0] = [[5,6],[67,9]]
print(b)

ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.