In [1]:
import numpy as np

In [11]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,4,3],[4,5,6,6]])
print(b)

[[1 2 4 3]
 [4 5 6 6]]


In [7]:
#Get dimensions
b.ndim

2

In [9]:
# Get shape
a.shape

(3,)

In [12]:
# Get Type
a.dtype

dtype('int16')

In [15]:
# Get total size
a.nbytes

6